### ISSUE TITLE
yolotest.py file is empty

### ISSUE THREAD

**Issue by rouderaa** [AronAyub/YoloV8-Pi-5#1]
Hi,
Have a look at the yolotest.py file please. Currently it is empty.
Kind regards,
  Rob

**Comment by AronAyub** [comment]
Hi @rouderaa , be on the look, i will commit that. With a local image or video, and also with a camera live source.

Regards,
Aron

**Comment by AronAyub** [comment]
Hi @rouderaa , check out on the new commit, let me know if the sample code helps you.

**Comment by rouderaa** [comment]
Hi Aron,
Thanks for filling the yolotest.py file. Could be a bit more extensive. I found the examples directory in the yolov8 directory so I am good now (https://github.com/ultralytics/ultralytics/tree/main/examples)
Kind regards,
  Rob

**Comment by AronAyub** [comment]
Thank you for the official link, it's useful !
